let BASE_URL = 'http://localhost:7171';

switch (process.env.NODE_ENV) {
  case 'development':
    BASE_URL = 'http://localhost:7171';
    break;

  default:
    break;
}

const USER_BASE_PATH = 'users';
export const USER_ENDPOINTS = {
  AUTHENTICATE: `${BASE_URL}/${USER_BASE_PATH}/authenticate`,
  GET_USER: `${BASE_URL}/${USER_BASE_PATH}/simpleUser`,
  GET_USER_BY_USERNAME: `${BASE_URL}/${USER_BASE_PATH}/user`,
  GET_USER_WITH_SECTOR: `${BASE_URL}/${USER_BASE_PATH}`,
  GET_ALL_USERS: `${BASE_URL}/${USER_BASE_PATH}/all`,
  GET_ALL_USERS_IN_SECTOR: `${BASE_URL}/${USER_BASE_PATH}/all/sector`,
  GET_ALL_USERS_IN_COMPANY: `${BASE_URL}/${USER_BASE_PATH}/all/company`,
  SET_WORK_VISIBLE_FOR_USER: `${BASE_URL}/${USER_BASE_PATH}/setWorkVisible`,
  SAVE_USER: `${BASE_URL}/${USER_BASE_PATH}/save`
};

const ARRANGEMENT_BASE_PATH = 'arrangements';
export const ARRANGEMENT_ENDPOINTS = {
  SAVE_NEW_ARRANGEMENT: `${BASE_URL}/${ARRANGEMENT_BASE_PATH}`,
  GET_ALL_ARRANGEMENTS_FOR_USER: `${BASE_URL}/${ARRANGEMENT_BASE_PATH}/all`,
  ADD_PARTICIPANT_TO_ARRANGEMENT: `${BASE_URL}/${ARRANGEMENT_BASE_PATH}/addParticipant`,
  REMOVE_PARTICIPANT_TO_ARRANGEMENT: `${BASE_URL}/${ARRANGEMENT_BASE_PATH}/removeParticipant`
};

const WORK_BASE_PATH = 'work';
export const WORK_ENDPOINTS = {
  SAVE_TASK: `${BASE_URL}/${WORK_BASE_PATH}`,
  GET_ALL_TASKS: `${BASE_URL}/${WORK_BASE_PATH}/all`,
  REMOVE_TASK: `${BASE_URL}/${WORK_BASE_PATH}/remove`,
  GET_TASK_WITH_USER_FOR_USER: `${BASE_URL}/${WORK_BASE_PATH}`,
  GET_TASKS_FOR_USER: `${BASE_URL}/${WORK_BASE_PATH}/tasks`,
  GET_TASK_WITH_FEEDBACK_LIST: `${BASE_URL}/${WORK_BASE_PATH}`,
  SET_TASK_TO_FINISHED: `${BASE_URL}/${WORK_BASE_PATH}`
};

const SECTOR_BASE_PATH = 'sector';
export const SECTOR_ENDPOINTS = {
  SAVE_SECTOR: `${BASE_URL}/${SECTOR_BASE_PATH}`,
  FIND_BY_ID: `${BASE_URL}/${SECTOR_BASE_PATH}`,
  GET_OFFERED_SERVICES_FOR_SECTOR: `${BASE_URL}/${SECTOR_BASE_PATH}/services`,
  AUTHENTICATE: `${BASE_URL}/${SECTOR_BASE_PATH}/authenticate`
};

const COMPANY_BASE_PATH = 'company';
export const COMPANY_ENDPOINTS = {
  SAVE_NEW_COMPANY: `${BASE_URL}/${COMPANY_BASE_PATH}`,
  FIND_COMPANY_BY_ID: `${BASE_URL}/${COMPANY_BASE_PATH}`,
  DELETE_COMPANY_BY_ID: `${BASE_URL}/${COMPANY_BASE_PATH}`,
  DELETE_SECTOR_FROM_COMPANY: `${BASE_URL}/${COMPANY_BASE_PATH}`,
  ADD_SECTOR_TO_COMPANY: `${BASE_URL}/${COMPANY_BASE_PATH}`,
  GET_OFFERED_SERVICES_FOR_COMPANY: `${BASE_URL}/${COMPANY_BASE_PATH}/services`,
  GET_COMPANIES_FOR_NEEDED_SERVICE: `${BASE_URL}/${COMPANY_BASE_PATH}/serviceNeeded`
};
